version: "3.9"

services:
  frontend:
    container_name: frontend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    restart: unless-stopped
    env_file:
      - .env
    networks:
      - public-network

networks:
  public-network:
    external: true
