version: "3.9"

services:
  frontend:
    container_name: frontend
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file:
      - .env
    networks:
      - public-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.frontend.rule=Host(`ame-tama.com`)"
      - "traefik.http.routers.frontend.entrypoints=websecure"
      - "traefik.http.routers.frontend.tls.certresolver=letsencrypt"
      - "traefik.http.services.frontend.loadbalancer.server.port=3000"

networks:
  public-network:
    external: true
