version: "3.9"

services:
  frontend:
    container_name: frontend
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file:
      - .env
    networks:
      - public-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.frontend.rule=Host(`ame-tama.com`)"
      - "traefik.http.routers.frontend.entrypoints=websecure"
      - "traefik.http.routers.frontend.tls.certresolver=letsencrypt"
      - "traefik.http.services.frontend.loadbalancer.server.port=3000"
          # تنظیم میدیلفایر فشرده‌سازی (Gzip)
      - "traefik.http.middlewares.compress.compress=true"
      - "traefik.http.routers.frontend.middlewares=compress"
       # ریدایرکت از www.ame-tama.com به ame-tama.com
      - "traefik.http.routers.redirect-www.rule=Host(`www.ame-tama.com`)"
      - "traefik.http.routers.redirect-www.entrypoints=websecure"
      - "traefik.http.routers.redirect-www.middlewares=www-redirect"
      
      # تنظیمات برای میدل‌ویر ریدایرکت
      - "traefik.http.middlewares.www-redirect.redirectscheme.scheme=https"
      - "traefik.http.middlewares.www-redirect.redirectscheme.permanent=true"
      - "traefik.http.middlewares.www-redirect.redirectscheme.destination=https://ame-tama.com"
    deploy:
      resources:
        limits:
          cpus: "2.5"
          memory: 4096M


networks:
  public-network:
    external: true
