networks:
  public-network:
    external: true

volumes:
  imgcache:

services:
  frontend:
    container_name: frontend
    build:
      context: ..
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file:
      - ../.env
    networks:
      - public-network
    labels:
      - "traefik.enable=true"

      # =========================
      # main router (non-www)
      # =========================
      - "traefik.http.routers.frontend.rule=Host(`ame-tama.com`)"
      - "traefik.http.routers.frontend.entrypoints=websecure"
      - "traefik.http.routers.frontend.tls.certresolver=letsencrypt"
      - "traefik.http.routers.frontend.service=frontend"
      - "traefik.http.routers.frontend.middlewares=compress"
      - "traefik.http.services.frontend.loadbalancer.server.port=3000"

      # compression middleware
      - "traefik.http.middlewares.compress.compress=true"

      # =========================
      # redirect www -> non-www
      # =========================
      - "traefik.http.routers.frontend-www.rule=Host(`www.ame-tama.com`)"
      - "traefik.http.routers.frontend-www.entrypoints=websecure"
      - "traefik.http.routers.frontend-www.tls.certresolver=letsencrypt"
      - "traefik.http.routers.frontend-www.middlewares=redirect-to-nonwww"

      - "traefik.http.middlewares.redirect-to-nonwww.redirectregex.regex=^/(.*)"
      - "traefik.http.middlewares.redirect-to-nonwww.redirectregex.replacement=https://ame-tama.com/$$1"
      - "traefik.http.middlewares.redirect-to-nonwww.redirectregex.permanent=true"

  nginx-imgcache:
    image: nginx:alpine
    container_name: nginx-imgcache
    restart: unless-stopped
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - imgcache:/var/cache/nginx
    networks:
      - public-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.imgproxy.rule=Host(`img.ame-tama.com`)"
      - "traefik.http.routers.imgproxy.entrypoints=websecure"
      - "traefik.http.routers.imgproxy.tls.certresolver=letsencrypt"
      - "traefik.http.services.imgproxy.loadbalancer.server.port=80"

  # imgproxy now internal only
  imgproxy:
    image: ghcr.io/imgproxy/imgproxy:latest
    container_name: image-proxy
    restart: unless-stopped
    environment:
      IMGPROXY_AUTO_WEBP: "true"
      IMGPROXY_AUTO_AVIF: "true"
    networks:
      - public-network
