events {}

http {

  proxy_cache_path /var/cache/nginx
    levels=1:2
    keys_zone=imgcache:100m
    max_size=20g
    inactive=365d
    use_temp_path=off;

  server {

    listen 80;

    location / {

      proxy_cache imgcache;

      proxy_cache_valid 200 365d;

      proxy_cache_use_stale error timeout updating http_500 http_502 http_503 http_504;

      proxy_ignore_headers Cache-Control;

      add_header X-Cache-Status $upstream_cache_status;

      proxy_pass http://image-proxy:8080;

    }

  }

}